src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity
 * @ORM\Table(name="orders")
 */
class Order
{

    const STATUS_DRAFT = 0;
    const STATUS_ORDERED = 1;
    const STATUS_SENT = 2;
    const STATUS_DONE = 3;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $dateTime;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", options={"default": 0})
     */
    private $status;


    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default": 0})
     */
    private $paymentState;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="orders")
     * @ORM\JoinColumn()
     */
    private $user;
    /**
     * @var float
     *
     * @ORM\Column(type="decimal", precision=10, scale=2, options={"default": 0})
     */
    private $sumOrder;

    /**
     * @var OrderItem[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\OrderItem", mappedBy="order")
     */
    private $items;


    public function __construct()
    {
        $this->status = self::STATUS_DRAFT;
        $this->dateTime = new \DateTime();
        $this->paymentState = false;
        $this->sumOrder = 0;
        $this->items = new ArrayCollection();
    }


    public function getId()
    {
        return $this->id;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->dateTime;
    }

    public function setDateTime(\DateTimeInterface $dateTime): self
    {
        $this->dateTime = $dateTime;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->Status;
    }

    public function setStatus(int $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getPaymentState(): ?bool
    {
        return $this->paymentState;
    }

    public function setPaymentState(?bool $paymentState): self
    {
        $this->paymentState = $paymentState;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSumOrder()
    {
        return $this->sumOrder;
    }

    public function setSumOrder($sumOrder): self
    {
        $this->sumOrder = $sumOrder;

        return $this;
    }



    /**
     * @return Collection|OrderItem[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(OrderItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setOrder($this);
            $this->updateValueOrder();
        }
        return $this;
    }

    public function removeItem(OrderItem $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getOrder() === $this) {
                $item->setOrder(null);
            }
            $this->updateValueOrder();
        }
        return $this;
    }
    public function updateValueOrder()
    {
        $total = 0;

            foreach ($this->items as $item) {
                $total += $item->getvalueOrder();
            }
        $this->sumOrder = $total;
    }

    public function getProductsCount()
    {
        $count = 0;
        foreach ($this->items as $item){
            $count += $item->getQuantityOrder();
        }
        return $count;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;


use App\Entity\OrderItem;
use App\Entity\Product;
use App\Service\Orders;
use http\Exception\InvalidArgumentException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class OrderController extends Controller
{
    /**
     * @Route("/cart/add/{id}/{quantityOrder}", name="order_add_to_cart")
     */
    public function addToCard(
        Product $product,
        Orders $orders,
        Request $request,
        $quantityOrder = 1)
    {
        $orders->addToCart($product, $quantityOrder, $this->getUser());

        if ($request->isXmlHttpRequest()){
            return$this->render('order/header_cart.html.twig',[
                'cart' => $orders->getCart(),
            ]);
        }


        return $this->redirect($request->headers->get('referer','/'));

    }

    /**
     *
     * @Route("/order", name="order")
     */
    public function order(Orders $orders)
    {
       $cart = $orders->getCart($this->getUser());
        return $this->render('order/cart.html.twig', [
            'cart'=> $cart
        ]);

    }

    /**
     * @Route("/cart/header", name="order_header_cart")
     */
    public function headercart(Orders $orders){
        return$this->render('order/header_cart.html.twig',[
        'cart' => $orders->getCart(),
    ]);
    }

    /**
     *@Route("/order/item/delete/{id}", name ="order_delete")
     */
        public function removeFromCart(Orders $orders, OrderItem $item)
        {
          $cart = $orders->removeFromCart($item);

            return $this->render('order/cart_table.html.twig', [
                'cart' => $cart,
            ]);

        }

    /**
     * @Route("/cart/update/{id}/{quantity}", name="order_update_item_quantity")
     */
        public function updateCartItemQuantity(Orders $orders, OrderItem $item, $quantity)
        {
            $quantity=(int)$quantity;

            if ($quantity <= 0) {
                $quantity = $item->getQuantityOrder();

            }

            $cart = $orders->updateCartItemQuantity($item, $quantity);

                return $this->render('order/cart_table.html.twig', [
                    'cart' => $cart,
                ]);

        }
}

templates/order/cart.html.twig
{% extends 'base.html.twig' %}

{% block body %}

        <h1>Корзина</h1>
<div id="cartTable">
    {{ include('order/cart_table.html.twig', {'cart':cart}) }}
</div>


    <div class="modal" id="confirmationModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Подтверждение удаления</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Действительно удалить товар из корзины?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отменить</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmedRemoveFromCartButton">Удалить</button>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/order/cart_table.html.twig
<table class="table">
    <tr>
        <th>Товар</th>
        <th>Цена</th>
        <th>кол-во</th>
        <th>Стоимость</th>

    </tr>

    {% for item in cart.items %}


        <tr>
            <td>{{ item.product.title }}</td>
            <td>{{ item.price }}</td>
            <td><input type="number" value="{{ item.quantityOrder}}" min="1" class="form-control-static js-cart-item-quantity"
                       data-item-update-url="{{ path('order_update_item_quantity', {'id':item.id, 'quantity': '--quantity--'}) }}">
            </td>
            <td>{{ item.valueOrder }}</td>
            <td><a href="{{ path('order_delete', {'id': item.id}) }}"
                   class="btn btn-danger js-remove-from-card"
                   data-toggle="modal" data-target="#confirmationModal"
                >Удалить</a>
            </td>
        </tr>
    {% endfor %}
    <tr>
        <th colspan="3">Всего</th>
        <th>{{ cart.sumOrder}}
    </tr>
</table>

templates/order/header_cart.html.twig
<a href="{{ path('order') }}">
<i class="fas fa-shopping-cart"></i>

{%- if cart.productsCount > 0 -%}
<span class="badge badge-light">{{ cart.productsCount }}</span>
    {{ cart.sumOrder }}
{%- endif -%}
</a>

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/OrderController.php'|file_link(0) }}">src/Controller/OrderController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/order/index.html.twig'|file_link(0) }}">templates/order/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}